### ISSUE TITLE
Tenent_id null on User Registration

### ISSUE THREAD

**Issue by manishlok** [iAmKevinMcKee/fire#2]
Hi, It was very helpful to understand some good concepts in laravel. I watched your video from laravel meetup. I am practicing to learn more from your codebase. While doing so,
I am getting an issue on user registration. tenant_id doesn't get stored in users table but tenant is created in tenant table. 
Can you suggest me what is going wrong?

**Comment by iAmKevinMcKee** [comment]
@manishlok make sure you not only create the event listener, but register it in the EventServiceProvider.

**Comment by manishlok** [comment]
Thanks for your reply. I found a way to set tenant_id . I am closing the issue.
Your help to new learner in laravel is appreciable.
